name: VULNERABILITIES-CHECK-CYCLE

on:
  pull_request:
    types:
      - push
    branches:
      - develop

env:
  #ENTANDO_OPT_USE_PPL_TAG: "v1.3.0"
  LOCAL_CLONE_DIR: "local-checkout"
  
jobs:
  checking-out:
    runs-on: ubuntu-latest
    env:
      ENTANDO_BOT_TOKEN: ${{ secrets.ENTANDO_BOT_TOKEN }}
    steps:
      - name: "CHECKOUT"
        id: CHECKOUT
        run: |
        #${{ secrets.ENTANDO_OPT_PPL_INSTALL_CMD }}
          bash <(curl -qsL "https://raw.githubusercontent.com/entando/entando-pipelines/v1.3.0/macro/install.sh")
          #Remove line above
          ~/ppl-run checkout-branch \
            --lcd "$LOCAL_CLONE_DIR" \
            --token "$ENTANDO_BOT_TOKEN" \
          ;
          ~/ppl-run generic GENERATE-BUILD-CACHE-KEY "BUILD_CACHE_KEY" --lcd "$LOCAL_CLONE_DIR" >> $GITHUB_ENV