name: VULNERABILITIES-CHECK-CYCLE

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop

env:
  ENTANDO_OPT_USE_PPL_TAG: "v1.3.0"
  LOCAL_CLONE_DIR: "local-checkout"
  
jobs:
  checking-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Listing files after checkout
        run: |
          pwd
          ls -a
      - name: Installing Snyk
        uses: snyk/actions/setup@0.3.0
      - name: Building auxiliary pom
        run: sh scan-prj/build-pom.sh
      - name: Run Snyk to check for vulnerabilities
        run: |
          cd scan-prj
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        