name: VULNERABILITIES-CHECK-CYCLE

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop

env:
  ENTANDO_OPT_USE_PPL_TAG: "v1.3.0"
  LOCAL_CLONE_DIR: "local-checkout"
  
jobs:
  checking-out:
    runs-on: ubuntu-latest
    steps:
      - name: Listing Files Before Checkout
        run: |
          pwd
          ls -a
      - name: "CHECKOUT"
        uses: actions/checkout@v3
      - name: Listing Files After Checkout
        run: |
          pwd
          ls -a
        