name: VULNERABILITIES-CHECK-CYCLE

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - develop

env:
  ENTANDO_OPT_USE_PPL_TAG: "v1.3.0"
  LOCAL_CLONE_DIR: "local-checkout"
  
jobs:
  checking-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Listing files after checkout
        run: |
          pwd
          ls -a
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@v0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}